import type { ArchiveManifest, MessageRecord } from "../types";
import { replaceAllMessages, replaceAllThreads, saveManifest, saveDirectoryHandle } from "./idb";
const chatId = -90001;
const passages = [
  "The discipline of seeing clearly\n\nA useful archive does more than preserve what was said. It lets us return to a thought with enough distance to notice what we missed the first time.\n\nContext is not decoration. It changes what a sentence means.\n\nRead the claim. Follow its source. Look at the surrounding conversation. The most revealing detail is often the one that disappears when a sentence travels alone.",
  "A reply is another way in\n\nA conversation is rarely a straight line. Someone returns to an older idea, adds a qualification, or asks the question that changes the frame.\n\nFollowing a quote back to its source restores that missing thread.",
  "Keep the question open\n\nCertainty arrives quickly. Understanding takes a little longer. Save the passages that deserve a second reading, including the ones you are not ready to agree with.\n\nA bookmark can mark a question as easily as an answer.",
  "A quiet place to gather ideas\n\nSelect a sentence to save it. Write a note in your own words. Gather related passages into a collection with an introduction that explains what connects them.\n\nYour reading library can become a map of the questions you are following.",
  "One thought at a time\n\nA modest reading session leaves room to reflect. Set a boundary of five posts, a few minutes, or an ending date. You can always continue when you are ready.\n\nFinishing a post is different from merely seeing it. Make that distinction your own.",
  "Return with fresh eyes\n\nReading is a conversation between an idea and your changing understanding. Mark a post to revisit when it asks a question you cannot answer yet.\n\nGood notes do not need to be long. A single connection can be enough.",
  "A longer meditation on attention\n\n" + Array.from({length:14},(_,i)=>`Reflection ${i+1}. Attention is a limited resource. Reading carefully means deciding what deserves it, following the connections that matter, and giving yourself time to let a thought settle. An archive helps when it preserves context and makes returning effortless. It becomes more useful when you can make it your own, without losing the original words.`).join("\n\n"),
  "Leave a trail\n\nGo back to your previous passage after following a source. Use the forward button to retrace the detour. Keep the original question close while exploring another perspective.",
  "The value of a good question\n\nAn interesting question brings ideas into conversation. Search beside the current post, read the surrounding context, then return to the sentence you started with.",
  "Enough for today\n\nThere is no prize for rushing through an archive. Understanding grows from attention, reflection, and returning. Save your place, keep a backup of your notes, and come back when you are ready."
];
export const DEMO_MESSAGES:MessageRecord[]=passages.map((text,index)=>{
  const id=index+1;const date=`2026-09-${String(20+Math.floor(index/2)).padStart(2,'0')}T09:00:00Z`;
  return {archive_version:1,chat_id:chatId,chat_username:null,chat_title:"The considered archive · Sample",chat_type:"Channel",message_key:`${chatId}:${id}`,message_id:id,message_type:"Message",date_utc:date,edit_date_utc:null,text,text_length:text.length,post_author:null,sender_id:null,from_id:null,grouped_id:null,views:null,forwards:null,permalink:null,media_kind:null,media_present:false,media_path:null,media_download_error:null,external_urls:[],media_raw:null,reply_parent_id:id===2?1:null,reply_to_msg_id:id===2?1:null,reply_to_top_id:null,reply_to_peer_id:null,is_reply:id===2,is_quote_reply:id===2,quote_text:id===2?"Context is not decoration. It changes what a sentence means.":null,quote_text_length:id===2?58:0,quote_offset_utf16:null,quote_entities:[],reply_header:null,reply_counts:{replies:null,channel_id:null,recent_repliers:null},thread_root_id:id===2?1:id,thread_key:`${chatId}:${id===2?1:id}`,reply_parent_key:id===2?`${chatId}:1`:null,search_text:text.toLowerCase()};
});
const manifest:ArchiveManifest={archive_version:1,exported_at_utc:"2026-09-30T00:00:00Z",source:{chat_input:"Sample",chat_id:chatId,chat_title:"The considered archive · Sample",chat_username:null,chat_type:"Channel",session_name:"sample"},files:{messages:"messages.jsonl",media_dir:null},counts:{messages:10,media_downloaded:0,media_download_failures:0},range:{first_message_id:1,first_message_date_utc:DEMO_MESSAGES[0].date_utc,last_message_id:10,last_message_date_utc:DEMO_MESSAGES[9].date_utc},options:{download_media:false,include_raw:false,limit:null}};
/** Only offered when there is no imported archive. */
export async function loadSampleArchive():Promise<void>{
  await replaceAllMessages(DEMO_MESSAGES);
  await replaceAllThreads(DEMO_MESSAGES.filter(m=>m.message_id!==2).map(m=>({thread_key:m.thread_key,chat_id:chatId,root_message_id:m.message_id,root_message_key:m.message_key,root_missing:false,first_message_id:m.message_id,first_message_date_utc:m.date_utc,last_message_id:m.message_id===1?2:m.message_id,last_message_date_utc:m.date_utc,message_count:m.message_id===1?2:1,preview_text:m.text,has_media:false,has_quote_replies:m.message_id===1,has_replies:m.message_id===1})));
  await saveManifest(manifest);await saveDirectoryHandle(null);
}
