export type GuideTopic = "basic" | "reading" | "library" | "search" | "appearance" | "account";

export interface TourStep {
  id: string;
  title: string;
  body: string;
  tip?: string;
  mobileBody?: string;
  target: string;
  actionLabel?: string;
}

export const GUIDE_TOPICS: Array<{ id: GuideTopic; title: string; description: string; icon: string }> = [
  { id: "basic", title: "Restart basic tour", description: "Search, save, mark seen, and find every reading tool.", icon: "00" },
  { id: "reading", title: "Find your reading rhythm", description: "Resume a passage, follow context, and decide what you have finished.", icon: "01" },
  { id: "library", title: "Keep and connect ideas", description: "Save passages, make notes, and build your own reading paths.", icon: "02" },
  { id: "search", title: "Explore without losing your place", description: "Search beside the text, read surrounding posts, and return.", icon: "03" },
  { id: "appearance", title: "Make the reader your own", description: "Explore four themes, four navigation positions, page presets, and backup.", icon: "04" },
  { id:"account",title:"Keep your place across devices",description:"Guest reading, verified accounts, and saving across devices.",icon:"05" }
];

const target = (name: string) => `[data-tour="${name}"]`;

export const TOUR_STEPS: Record<GuideTopic, TourStep[]> = {
  basic: [
    {id:"basic-navigation",title:"Welcome to vn reader",body:"Read Vidurneeti’s posts in order, follow conversations in Threads, revisit Bookmarks, or explore Progress. Choose a view in the navigation.",mobileBody:"Tap the menu to switch between Read, Threads, Bookmarks and Progress. Read follows Vidurneeti’s posts in order; Threads follows conversations.",target:target("navigation")},
    {id:"basic-search",title:"Find a thought",body:"Choose Search to find a post or a command. On a keyboard, Ctrl+K or ⌘K opens the same search.",mobileBody:"Tap the magnifying glass to search posts and threads, or jump to a reading tool. Tap a result to open it; no keyboard shortcuts are needed.",target:target("search")},
    {id:"basic-actions",title:"Keep what matters",body:"Save keeps a post in Bookmarks so you can find it again. Mark seen records that you have read it; tap Seen again to undo. More lets you add a note, save it for later, or read nearby posts. Your place is saved automatically as you scroll.",target:target("reading-state")},
    {id:"basic-tools",title:"Your tools, when you need them",body:"Tools keeps the extras together: Resume your place, your saved library, search beside the text, and reading history. Width makes the text column narrower or wider. You can simply read, save and mark seen; the other tools are optional.",target:target("reading-tools")},
    {id:"basic-help",title:"Come back whenever you like",body:"Open Menu → Help & tours to restart this basic tour or explore detailed tours of reading, notes, search, settings and accounts. Appearance and your account live in the same menu.",tip:"You can skip a tour and replay it later. Your reading place and saved work are preserved.",target:target("help")}
  ],
  account: [
    {id:"account-guest",title:"Read freely as a guest",body:"Your notes, queue, collections, bookmarks, and reading position stay in this browser while you read as a guest. No email is required. Clearing browser storage removes the guest copy.",tip:"Settings → Export reading backup keeps a separate copy of your work.",target:target("account-controls")},
    {id:"account-login",title:"Verify your email, then use your password",body:"Open the account button, choose Create an account, and enter your email and a password of at least 12 characters. Enter the six-digit code from your inbox to verify. Sign in with that email and password on another device. Forgot password sends a reset code.",tip:"If email delivery is not connected, guest reading remains available.",target:'[data-tour="account-controls"], [data-tour="account-status"]'},
    {id:"account-sync",title:"Know where your progress is saved",body:"The account panel shows Saving, Saved across devices, or Sync pending. Pending changes are kept in an account-specific device cache and retried when online. Your account panel can bring the browser guest copy into the account after you choose it. Signing out returns to your separate guest copy.",tip:"If two devices edit the same information, choose the copy to keep in the account panel. Export a backup first if you want both.",target:target("account-status")}
  ],
  reading: [
    { id: "reading-timeline", title: "Explore when VN posted", body: "Progress opens the entire posting timeline. Use the range buttons for a year, six months, three months, one month, or any Monday–Sunday week. Areas stack the cumulative totals by post type; the dashed line shows posts containing links without counting them twice in the stack. The lower bars show weekly activity. Hover a week to preview its breakdown; click or tap to keep the details open, then choose Explore this week. Dismiss the preview or click outside to close it. Turn on Show individual posts for post previews. Ctrl-scroll or pinch to zoom, and drag to pan. On mobile, Read this post is the explicit action that opens the exact post.", tip: "Links can overlap with media types. Dates use IST. Reset zoom restores the selected range. Use Back to return to Progress.", target: target("post-timeline") },
    { id: "reading-navigation", title: "One archive, four ways in", body: "Read follows the archive in order. Threads groups conversations. Bookmarks holds posts you save with the bookmark icon. Progress shows your seen history. Use the same views wherever you place the navigation.", tip: "Next reveals each control for you. This tour does not change your notes, reading states, or queue.", target: target("navigation") },
    { id: "reading-resume", title: "Return to the passage, not just the post", body: "Choose Resume your place to return to the saved paragraph and position. Your place is saved as you read, including inside a long post; reopening the reader brings you back.", tip: "Changing the theme or column width keeps the reading anchor with the text.", target: target("reading-tools") },
    { id: "reading-state", title: "Seeing is different from finishing", body: "Seen follows your Seen till here marker and individual Mark seen or Mark unseen overrides. Scrolling alone does not mark a post finished. Use More → Reading state to choose In progress, Finished, or Revisit yourself. Choose Finished when you are satisfied with the idea; it also removes that post from Read later.", tip: "More → Mark everything up to here seen marks the preceding posts seen. It does not mark them Finished.", target: target("reading-state") },
    { id: "reading-context", title: "Follow the conversation", body: "A post's context tells you its thread and reply source. Open thread opens a conversation outline. “You’re here” marks the current post; choose another row to read it. On a phone, choosing a post closes the panel. When a quoted source is available, choose its quote to preview it beside your reading, then expand it if you need more.", tip: "A missing source is identified as missing; the reader cannot reconstruct text absent from the archive.", target: target("source-context") },
    { id: "reading-trail", title: "Make a detour and come back", body: "Back and Forward follow your reading trail after opening a post or conversation. The return label names the location you can get back to. Read nearby posts opens a post with its neighbours so you can understand the surrounding context.", tip: "Use the trail after expanding a source or opening a saved post.", target: target("reading-tools") },
    { id: "reading-session", title: "Give a session a gentle boundary", body: "Choose Posts, Reading minutes, or Until date, enter your target, then Set boundary. The stream ends at a post boundary rather than halfway through an idea. Clear boundary restores the full stream.", tip: "Reading minutes is an estimate from the text, not a countdown timer.", target: target("session") },
    { id: "reading-focus", title: "Keep only the reading close", body: "The focus button hides navigation views, reading tools, session controls, and post actions. Width stays available to adjust the reading column. Use the same button or Exit focus to bring them back whenever you want to save, search, or change settings.", tip: "You can replay any tour from Help & tours whenever you need a reminder.", target: target("focus") }
  ],
  library: [
    { id: "library-save", title: "Keep the sentence that matters", body: "Select text inside a post. The Save passage control appears beside your selection; choose it to keep that exact passage in your library. Saved passages are highlighted when you return to the text.", tip: "The bookmark icon saves the whole post. A passage keeps the specific words you selected.", target: target("passages") },
    { id: "library-notes", title: "Write the connection in your own words", body: "Choose More → Add note below a post, write your thought, then Save note. Edit note lets you revise it. Your note belongs to that post; saved passages can also receive their own notes in My work.", tip: "Saving an empty post note removes that note. The original archive text stays unchanged.", target: target("reading-state") },
    { id: "library-queue", title: "Read later is your next-read queue", body: "Choose More → Read later below any post to put it in this queue. Open My library, then Read later. Earlier and Later arrange your order; Open post returns to the text. Remove from queue clears an item without deleting the post.", tip: "Marking a queued post Finished removes it from the queue automatically. Bookmarks remain separate.", target: target("library-panel") },
    { id: "library-collections", title: "Turn saved ideas into a reading path", body: "In Collections, choose New collection, give it a name and optional introduction, and save. Expand Add a post or passage to find posts by ID or words, or choose a saved passage. Earlier and Later set the order of items.", tip: "Deleting a collection keeps your posts, notes, and saved passages. It removes only that named reading path.", target: target("library-panel") },
    { id: "library-work", title: "Search what you have thought about", body: "My work searches your personal notes, saved passages, and collection names and introductions. Open post takes you back to the source. Read nearby posts adds nearby posts when a saved sentence needs context.", tip: "This searches your own work. Use Search beside reading to search the archive itself.", target: target("library-panel") }
  ],
  search: [
    { id: "search-panel", title: "Search alongside your current passage", body: "Search beside reading opens this panel while keeping the reading stream visible. Enter a phrase or topic from the archive. Matching posts appear here; Read post opens a result and marks matching text in the stream.", tip: "Results show up to 100 matching posts. Refine your phrase to narrow a large result set.", target: target("search-panel") },
    { id: "search-context", title: "Read a result in context, then return", body: "Choose Read nearby posts on a result to see its surrounding posts. When you are done exploring, close this search panel with its × button to return to the passage where you started searching.", tip: "Your original return point is kept until the search panel closes.", target: target("search-panel") },
    { id: "search-commands", title: "Find your way quickly", mobileBody:"Tap the search icon to search posts, threads, or commands. Tap a result to open it. For a detour with a visible return point, open Reading tools → Search beside reading.", body: "The search icon opens Search and commands. Press ⌘K on Mac or Ctrl+K elsewhere for the same palette. Search posts and threads, jump to a result, or choose a command without hunting through the page.", tip: "Use the side search when you want a visible return point; the command palette is useful for a quick jump.", target: target("search") },
    { id: "search-threads", title: "Choose the view that fits the question", body: "Read is useful for chronology; Threads makes conversations easier to follow. Bookmarks returns to saved whole posts. Progress helps you check seen history. The reading trail brings you back after a change of view.", tip: "Themes and navigation position change presentation; all these reading tools work the same way in every theme.", target: target("navigation") }
  ],
  appearance: [
    { id: "appearance-themes", title: "Choose a material as well as a colour", body: "Select Vercel, Editorial, Cobalt Index, or Liquid Opal. Your first visit starts with Vercel in system dark mode or Liquid Opal in system light mode. Each brings its own surfaces, type accents, edges, and controls across the reader. Changes are applied immediately and saved on this device.", tip: "The controls and your reading data work the same way in all four themes. The theme reference in this guide explains each atmosphere.", target: target("themes") },
    { id: "appearance-navigation", title: "Put navigation where it suits you", body: "Choose Top, Bottom, Left, or Right. Top and Bottom keep views in a horizontal dock; Left and Right make a vertical rail. The page makes room for your choice, and search, focus, settings, and tours remain available.", tip: "Navigation position is independent of the theme and saved with your appearance preferences.", target: target("nav-placement") },
    { id: "appearance-type", title: "Give long text room to breathe", body: "Choose a serif, sans serif, or monospace reading font. Adjust text size, line spacing, paragraph spacing, and column width. The Read toolbar’s Width control also offers Narrow, Comfortable and Wide presets. Match the theme's surface, or use warm ivory or sepia. The preview lets you judge comfort before continuing.", tip: "These controls change the reading text without replacing the theme's navigation and interface styling.", target: target("typography") },
    { id: "appearance-media", title: "Decide how much media to see", body: "Compact previews keep images manageable. Full-width media gives visuals more room. Collapsed media stays tucked away until you open it. Audio and video controls remember playback position and speed when the media is available.", tip: "If media cannot load, try Retry media. Some archived files may be unavailable.", target: target("media") },
    { id: "appearance-presets", title: "Save a familiar reading setup", body: "Enter a name such as Evening reading and choose Save this setup. Applying a preset restores its theme, navigation position, page settings, media preference, and focus setting. You can keep up to twelve presets and remove ones you no longer use.", tip: "Presets are appearance setups, not copies of your notes or progress.", target: target("presets") },
    { id: "appearance-backup", title: "Carry your reading work with you", body: "Export reading backup saves progress, notes, saved passages, bookmarks, collections, queue, and preferences as a JSON file. Restore backup imports that saved reading state. Export your current state first if you want a copy before restoring.", tip: "Backups do not include archive posts or media files. Guest preferences stay in this browser; verified accounts sync them across devices.", target: target("backup") }
  ]
};

export const THEME_GUIDE = [
  { name: "Vercel", description: "An engineered reading space: dark monochrome surfaces, precise sans typography, shadow-framed panels, compact corners, and clear blue keyboard focus. Hover changes colour without moving the controls." },
  { name: "Editorial", description: "A quiet reading desk: restrained amber accents, bookish headings, and a compact framed dock." },
  { name: "Cobalt Index", description: "A precise archive index: electric blue navigation, grid structure, bold headings, and square controls." },
  { name: "Liquid Opal", description: "An airy reading space: pearl surfaces, soft iridescent light, generous curves, and pill-shaped controls." }
];

export const HELP_SECTIONS = [
  { title: "Start, resume, and change views", paragraphs: ["The hosted archive opens automatically. Start reading as a guest or sign in to keep your reading work in sync across devices.", "Read follows the archive; Threads groups related replies; Bookmarks stores whole posts saved with the bookmark icon; Progress shows seen history. Resume your place returns to your saved paragraph, including inside long posts."] },
  { title: "Seen, Finished, and reading sessions", paragraphs: ["Seen follows the posts you mark seen; scrolling alone does not update it. Mark seen beneath a post records that you read it; choose Seen to undo. More → Mark everything up to here seen marks preceding posts seen. Use normal seen status removes a manual exception.", "Reading state is your own judgement: Not started, In progress, Finished, or Revisit. Finished removes a post from Read later. Set a session boundary by number of posts, estimated reading minutes, or date; Clear boundary opens the full stream again."] },
  { title: "Quotes, references, and your reading trail", paragraphs: ["Choose an available quoted source to peek beside the current post. Expand source opens the full source. Open thread groups the conversation. Read nearby posts reveals nearby posts. Back and Forward follow your reading trail after a detour.", "More → References lists additional external links below a post. External links open outside your current reading. A source missing from the archive cannot be shown; its missing context is indicated."] },
  { title: "Passages, notes, and whole-post bookmarks", paragraphs: ["Select words in the reading text, then choose Save passage. More → Add note saves your own reflection. Edit note revises it; saving an empty note removes it. My work lists your saved passages and notes, with separate notes available for passages.", "The bookmark icon saves the whole post, separate from Read later. Bookmarks can have tags and notes. Removing a saved passage also removes that passage's references from collections; the original post stays in the archive."] },
  { title: "Read later and personal collections", paragraphs: ["More → Read later adds it to My library → Read later. Use Earlier and Later to choose the queue order. Finished or Remove from queue clears it without deleting the post or bookmark.", "My library → Collections → New collection creates a named list with an optional introduction. Add a post or passage adds your chosen items. Reorder items with Earlier and Later. Deleting a collection keeps the underlying posts, passages, and notes."] },
  { title: "Search the archive or your own work", paragraphs: ["Search beside reading keeps a side panel of archive results and highlights matches. Read post opens a result; Read nearby posts opens its context. Close the panel to return to the original passage. Up to 100 matches are shown, so narrow broad phrases.", "My library → My work searches notes, saved passages, and collection titles and introductions separately from archive text. The search icon or ⌘K / Ctrl+K opens Search and commands for quick jumps and commands."] },
  { title: "Appearance, navigation, focus, and media", paragraphs: ["Settings applies one of four themes globally. Your first visit follows the device: Vercel for dark mode and Liquid Opal for light mode. Your saved choice takes precedence on future visits. Top, Bottom, Left, and Right choose where the navigation sits independently of the theme. Text size, font, line spacing, paragraph spacing, width, and reading surface make the passage comfortable. Name and save up to twelve page presets.", "Focus hides surrounding navigation and post actions until you exit it. Compact, full-width, and collapsed media let you choose how much to see. For available audio and video, playback speed and position are remembered."] },
  { title: "Where your data lives and how to back it up", paragraphs: ["Guest reading data stays in this browser. With a verified account, notes, passages, collections, queue, progress, bookmarks, media position, and appearance sync across devices. The account panel shows saving status. Sign out to return to the separate guest copy. Use the account panel to deliberately bring guest progress into your account.", "Settings → Export reading backup saves progress, notes, passages, bookmarks, collections, Read later, and preferences. Restore backup restores that reading state from JSON. Export your current state before restoring if you want to keep a copy. Archive posts and media files are not included in the reading backup."] }
];
